### ISSUE TITLE
Software with "&" in the title

### ISSUE THREAD

**Issue by dannyhanes** [mondada/kinobi#5]
When adding software with an "&" symbol in the name, it removes all text after the &. 

For example, "Read&Write.app" becomes "Read"

**Comment by duncan-mccracken** [comment]
This issue is due to the escaping of html entities, it is resolved in the current (1.2) source code, and will be in the upcoming release of this version.

**Comment by dannyhanes** [comment]
Sounds good. In the meantime, how would you suggest I get proper reporting for the app? I have created an extension attribute which reports back the version number, but for the requirements (Criteria used to determine which computers in your environment have this software title installed.) I am not sure how to get it working.

**Comment by duncan-mccracken** [comment]
Jamf recommends using the bundle identifier for the application rather than the name, but that may also pose a problem.
You can get it to use an ampersand in the problem fields by using the URL encoded vale for an ampersand in the field name (short term). You'll just need to pay careful attention to edits.
e.g.
For "Read&Write.app"
Input "Read%26Write.app"
This should save correctly in the database and the subsequent definition.

**Comment by dannyhanes** [comment]
@duncan-mccracken Ah, that worked. Thanks!

**Comment by sjha967** [comment]
> When adding software with an "&" symbol in the name, it removes all text after the &.
> 
> For example, "Read&Write.app" becomes "Read"

https://krypted.com/utilities/html-encoding-reference/

**Comment by duncan-mccracken** [comment]
Addressed in 1.2 release
